### ISSUE TITLE
Fatal error: Unknown "emitToWithSelector" function

### ISSUE THREAD

**Issue by khromov** [clickfwd/yoyo-twig-app#1]
Running using PHP 8.0.3 and the following commands:

```
composer i
php -S localhost:8080 -t public/
```

When visiting http://localhost:8080/ the following error is displayed:

```
PHP Fatal error:  Uncaught Twig\Error\SyntaxError: Unknown "emitToWithSelector" function. in /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/app/resources/views/yoyo/wishlist.twig:1
Stack trace:
#0 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/twig/twig/src/ExpressionParser.php(455): Twig\ExpressionParser->getFunctionNodeClass('emitToWithSelec...', 1)
#1 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/twig/twig/src/ExpressionParser.php(235): Twig\ExpressionParser->getFunctionNode('emitToWithSelec...', 1)
#2 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/twig/twig/src/ExpressionParser.php(175): Twig\ExpressionParser->parsePrimaryExpression()
#3 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/twig/twig/src/ExpressionParser.php(70): Twig\ExpressionParser->getPrimary()
#4 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/twig/twig/src/Parser.php(128): Twig\ExpressionParser->parseExpression()
#5 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/twig/twig/src/Parser.php(84): Twig\Parser->subparse(NULL, false)
#6 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/twig/twig/src/Environment.php(479): Twig\Parser->parse(Object(Twig\TokenStream))
#7 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/twig/twig/src/Environment.php(507): Twig\Environment->parse(Object(Twig\TokenStream))
#8 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/twig/twig/src/Environment.php(348): Twig\Environment->compileSource(Object(Twig\Source))
#9 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/twig/twig/src/Environment.php(309): Twig\Environment->loadTemplate('__TwigTemplate_...', 'wishlist.twig')
#10 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/twig/twig/src/Environment.php(277): Twig\Environment->load('wishlist.twig')
#11 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/clickfwd/yoyo/src/yoyo/ViewProviders/TwigViewProvider.php(110): Twig\Environment->render('wishlist.twig', Array)
#12 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/clickfwd/yoyo/src/yoyo/ComponentManager.php(210): Clickfwd\Yoyo\ViewProviders\TwigViewProvider->__toString()
#13 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/clickfwd/yoyo/src/yoyo/ComponentManager.php(78): Clickfwd\Yoyo\ComponentManager->processAnonymousComponent(Array, Array)
#14 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/clickfwd/yoyo/src/yoyo/Yoyo.php(248): Clickfwd\Yoyo\ComponentManager->process('yoyo-gulp1cmj', 'wishlist', 'render', Array, Array)
#15 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/clickfwd/yoyo/src/yoyo/Yoyo.php(203): Clickfwd\Yoyo\Yoyo->output(false)
#16 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/clickfwd/yoyo/src/yoyo/helpers.php(13): Clickfwd\Yoyo\Yoyo->render()
#17 /Users/stanislav.khromov/Documents/GitHubPersonal/yoyo-twig-app/vendor/clickfwd/yoyo/src/yoyo/Twig/YoyoTwigExtension.php(47): Yoyo\yoyo_render('wishlist', Array, Array)
...
```

**Comment by khromov** [comment]
Appears to be solved if you bump `clickfwd/yoyo` to `0.7.2` - see:
https://github.com/clickfwd/yoyo-twig-app/pull/2/
